**Data Frame**

In [2]:
import pandas as pd
import numpy as np

*Creating a Dataframe*

Dictionary  
Creating dataframe from a dictionary, key becomes the header

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

List  
Creating dataframe from a list, header are default set as index  
For header, columns=*list having column title* is added in the function

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

*Selecting and Indexing of columns*

For one column a single ["*Column header*"] is required but for more list of list is required

In [5]:
# df2["Name"]
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

*Creating a new Columns*

*Dataframe*["*Column_header* "] = *list containing values*

In [8]:
df2["Designation"]=["Doctor","Eng","Doctor","Eng"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

*Removing Columns or Rows*

*Dataframe*.drop("*Column_name or Row_label*",axis=....)

axis is 0 in default so so axis should be given 1 to specify find the header of columns

In [9]:
df2.drop("Designation", axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

drop() just makes a copy of the dataframe rather than doing operations on the actual dataframe  
drop("*Column_name*",axis=1,inplace = True) is used for removing columns in the main data

In [10]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

In [11]:
df2.drop("Designation", axis=1, inplace= True)

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2.drop(0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

*Selecting a row*
loc -> location
iloc ->index location

In [18]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [20]:
df.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

*Selecting subsets of rows and columns*

*Dataframe*.loc[[*index of rows*]] [[*Column_ header*]]

In [26]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [28]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

*Conditional Selection*

*Dataframe*[*Data frame*[*Column Header*] *Condition*]

In [29]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
#Display data of age > 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [33]:
df2[(df2["Age"] > 30) & (df2["City"]== "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000