In [7]:
import pandas as pd
import numpy as np

**Data Frame Basic Operations**

In [8]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [9]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

*.shape*  
Attribute that gives no of rows and columns

In [11]:
df.shape

(5, 3)

*.columns*  
Gives list of column-header in dataframe

In [13]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

*.head()*  
Top rows

In [19]:
df.head(2)

   A   B    C
0  1  10  100
1  2  20  200

*.info()*  
Gives information i.e. Non-null, its count and data type of each column

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

*describe()*  
All statistical findings

In [16]:
df.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

*Broadcasting in a column*

In [17]:
df['B'] + 20

0    30
1    40
2    50
3    60
4    70
Name: B, dtype: int64

**Data Frames Applying Functions**

*.apply(function_name)*  
To use a user-defined function in the dataframe

In [21]:
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [23]:
def square(x):
    return x**2

In [24]:
df['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

The changes can also be updated in the main dataframe.  
Similarly a new column can be also created.

In [25]:
df['D'] = df['B'].apply(square)

In [26]:
df

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

lamda functions can also be used

In [27]:
df['C'].apply(lambda x: x + 100)

0    200
1    300
2    400
3    500
4    600
Name: C, dtype: int64